version: '3.9'

services:
  frontend:
    build: ./Client
    ports:
      - "5173:5173"
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - app-network

  backend1:
    build: ./Server
    expose:
      - "5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/url
      - PORT=5000
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - mongo
    networks:
      - app-network

  backend2:
    build: ./Server
    expose:
      - "5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/url
      - PORT=5000
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - mongo
    networks:
      - app-network

  backend3:
    build: ./Server
    expose:
      - "5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/url
      - PORT=5000
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
      - backend3
      - frontend
    networks:
      - app-network

volumes:
  mongo_data:


networks:
  app-network:
